### ISSUE TITLE
[JOSS] Python API method documentation lacking

### ISSUE THREAD

**Issue by adswa** [openneuropet/PET2BIDS#250] opened 2023-12-22 09:16 UTC
Although the usage notes say "Pypet2bids is primarily designed to run as a command line utility", the About page says "you’re more than able to use this tool as a Python library. For more information on usage individual methods or modules refer to [pypet2bids package](https://pet2bids.readthedocs.io/en/latest/pypet2bids.html#pypet2bids-package)." Given that usage of individual python functions or modules is mentioned, suitable documentation would be needed. The documentation currently exposes the pypet2bids modules, but they contain barely any documentation:

![image](https://github.com/openneuropet/PET2BIDS/assets/29738718/2e88e550-d9ec-438c-b95d-d63c4517749c)

**Comment by bendhouseart** [comment] 2024-01-09 20:27
Hmm, so getting some import failures on RTD -> https://readthedocs.org/projects/pet2bids/builds/23066786/. Super cool.... Not sure what kicked this off and am, of course, unable to reproduce it locally when I run `make html` to generate the docs with autodoc. But, yes there should be stuff there...

**Comment by bendhouseart** [comment] 2024-01-18 17:39
Okay so a tragedy of errors here, rtd updated their build vm's, sphinx contrib for matlab had some bugs, and the import errors on rtd weren't occuring locally. Wish the status badge erred to red, but it doesn't account for sphinx... Fixed with pr #257, see https://pet2bids.readthedocs.io/en/latest/pypet2bids.html and https://pet2bids.readthedocs.io/en/latest/matlab.html

**Closed by bendhouseart** 2024-01-18 17:39 UTC
